package cc.cynara.oa.domain;

import java.util.Date;

//
//	文章
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Article.java
//  @ Date : 2016/4/21
//  @ Author :  remix-7
//
//

public abstract class Article {
	private Long id;
	private String content; //文章的内容Text 类型
	private User author;  //作者
	private Date postTime;  //发表时间
	private String ipAddr;  //发表ip
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public User getAuthor() {
		return author;
	}
	public void setAuthor(User author) {
		this.author = author;
	}
	public Date getPostTime() {
		return postTime;
	}
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}
	public String getIpAddr() {
		return ipAddr;
	}
	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}
	
}
