package cc.cynara.oa.domain;

import java.io.Serializable;
import java.util.Set;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Department.java
//  @ Date : 2016/4/17
//  @ Author : remix-7
//
//

public class Department implements Serializable{
	private Long id;//id自动生成
	private String name;//部门名称
	private String description;//说明
	private Set<User> users;//部门下面的用户
	private Department parent;//父级部门
	private Set<Department> childs;//子部门
	
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Set<User> getUsers() {
		return users;
	}
	public void setUsers(Set<User> users) {
		this.users = users;
	}
	public Department getParent() {
		return parent;
	}
	public void setParent(Department parent) {
		this.parent = parent;
	}
	public Set<Department> getChilds() {
		return childs;
	}
	public void setChilds(Set<Department> childs) {
		this.childs = childs;
	}
	
	
}
