package cc.cynara.oa.domain;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : privilege.java
//  @ Date : 2016/4/18
//  @ Author : remix-7
//
//
public class Privilege implements Serializable{
	private Long id;
	private Set<Role> roles = new HashSet<Role>();
	private Privilege parent;
	private Set<Privilege> childs = new HashSet<Privilege>();
	private String url;
	private String name;
	
	
	public Privilege() {
	}
	public Privilege( String name ,String url, Privilege parent) {
		this.name = name;
		this.url = url;
		this.parent = parent;
		
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Set<Role> getRoles() {
		return roles;
	}
	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}
	public Privilege getParent() {
		return parent;
	}
	public void setParent(Privilege parent) {
		this.parent = parent;
	}
	public Set<Privilege> getChilds() {
		return childs;
	}
	public void setChilds(Set<Privilege> childs) {
		this.childs = childs;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
}
