package cc.cynara.oa.domain;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reply.java
//  @ Date : 2016/4/21
//  @ Author :  remix-7
//
//

public class Reply extends Article {
	private Topic topic; //所属的主体
	private boolean deleted; //是否已经删除
	public Topic getTopic() {
		return topic;
	}
	public void setTopic(Topic topic) {
		this.topic = topic;
	}
	public boolean isDeleted() {
		return deleted;
	}
	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	
}
