package cc.cynara.oa.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//
//  主题
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Topic.java
//  @ Date : 2016/4/21
//  @ Author :  remix-7
//
//

public class Topic extends Article {
	/**普通贴*/
	public static final int TYPE_NORMAL = 0;
	/**精华贴*/
	public static final int TYPE_BAST = 1;
	/**置顶贴*/
	public static final int TYPE_TOP = 2;
	
	private String title;  //标题
	private int type;  //类型
	private Forum forum;   
	private Set<Reply> replys = new HashSet<Reply>();
	private int replyCount;  //回复数量
	private Reply lastReply; //最后回复
	private Date lastUpdateTime; //最后文章的发表时间
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type = type;
	}
	public Forum getForum() {
		return forum;
	}
	public void setForum(Forum forum) {
		this.forum = forum;
	}
	public Set<Reply> getReplys() {
		return replys;
	}
	public void setReplys(Set<Reply> replys) {
		this.replys = replys;
	}
	public int getReplyCount() {
		return replyCount;
	}
	public void setReplyCount(int replyCount) {
		this.replyCount = replyCount;
	}
	public Reply getLastReply() {
		return lastReply;
	}
	public void setLastReply(Reply lastReply) {
		this.lastReply = lastReply;
	}
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}
	
}
